<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260624120744 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_techno (project_id INT NOT NULL, techno_id INT NOT NULL, PRIMARY KEY (project_id, techno_id))');
        $this->addSql('CREATE INDEX IDX_2E230596166D1F9C ON project_techno (project_id)');
        $this->addSql('CREATE INDEX IDX_2E23059651F3C1BC ON project_techno (techno_id)');
        $this->addSql('CREATE TABLE techno (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE project_techno ADD CONSTRAINT FK_2E230596166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_techno ADD CONSTRAINT FK_2E23059651F3C1BC FOREIGN KEY (techno_id) REFERENCES techno (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project DROP technologies');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project_techno DROP CONSTRAINT FK_2E230596166D1F9C');
        $this->addSql('ALTER TABLE project_techno DROP CONSTRAINT FK_2E23059651F3C1BC');
        $this->addSql('DROP TABLE project_techno');
        $this->addSql('DROP TABLE techno');
        $this->addSql('ALTER TABLE project ADD technologies JSON NOT NULL');
    }
}
